server:
   port: 10001
   
environment:
    profile: dev 
    
xml:
    folderPath: slc-xmls
    
database:
    hsqldb:
        username: sa
        password:
        name: slc
        file: C:\temp\hsqldb.jar
    
    
